### ISSUE TITLE
Crash when updating to 0.6.2 from 0.6.1

### ISSUE THREAD

**Issue by bear989** [BluSunrize/ImmersiveEngineering#661]
everything is find with 0.6.1, nothing else updated or changed

Description: There was a severe problem during mod loading that has caused the game to fail
 
cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: minetweaker.MineTweakerImplementationAPI.onPostReload(Lminetweaker/util/IEventHandler;)Lminetweaker/api/event/IEventHandle;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoSuchMethodError: minetweaker.MineTweakerImplementationAPI.onPostReload(Lminetweaker/util/IEventHandler;)Lminetweaker/api/event/IEventHandle;
	at blusunrize.immersiveengineering.common.util.compat.minetweaker.MTHelper.postInit(MTHelper.java:47)
	at blusunrize.immersiveengineering.ImmersiveEngineering.postInit(ImmersiveEngineering.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 18 more

**Comment by theunkn0wn1** [comment]
... Do not paste your crashlog here!
=========
please, it makes things hard to read... Put it into a gist or pastebin it.

You have MineTweaker installed? Make sure it is up to date.

**Comment by bear989** [comment]
i/m using MT 3.0.10 the latest non DEV version, I have broke the pack down
to just IE and MT and it still doesn't work

**Comment by mindforger** [comment]
3.0.10b ? i remember a commit to be dependant to minimum this specific version or was this not included ind 0.6.2

**Comment by BluSunrize** [comment]
Yes, you need 3.0.10b. The "b" is important. This was mentioned in the changelog as well. Also I'm surprised this crashed, it should have caught it and just printed the error.

So yeah update your Minetweaker, I require a method in the new one.

**Comment by mindforger** [comment]
@BluSunrize because we are fiddling with unrecognized scripts, can you update the MT excavator page? we want to relaunch today but we did not manage to get the script running :(

**Comment by BluSunrize** [comment]
I don't write that page, @Yulife does.

**Comment by BluSunrize** [comment]
Feel free to hop on IRC though, I might be able to help you fix the script.

**Comment by mindforger** [comment]
are you there around 18:00 MEZ ?

**Comment by BluSunrize** [comment]
I'm around all day, mostly =P
