### ISSUE TITLE
(1.14.4) My IE crashes my game even with no other in it/it being by itself

### ISSUE THREAD

**Issue by jillv46** [BluSunrize/ImmersiveEngineering#3806]
So I want to use this mod but my game crashes. There is 2 updates for 1.14.4, The latest one (ImmersiveEngineering-0.14-94) requires a specific version of forge (says this in the changelog "Change minimum Forge version to 28.2.3") but the other update (ImmersiveEngineering-0.14-93) says nothing about forge/the changelog only says this "Initial Release for Minecraft 1.14.4". I can't use the newer one because forge 28.2.3 doesn't work on Optifine (The latest forge Optifine supports is 28.2.1) and I don't have a great PC/it's ok speed and I need Optifine with this mod. So I want to use the older update for this mod (since I assume it will work on a older version of forge/forge version 28.2.1) but even with mod by itself with the older update of this mod using forge versions 28.2.0, 28.2.1, and 28.2.2 my game crashes and I want to know why. 

A helper on the Minecraft discord support told me that the issue is this 
"yeah i cant get much more from that than Immersive Engineering is the cause and java.lang.NoClassDefFoundError: net/minecraftforge/client/model/IModelLoader is the error" 

and he said this 
"it also seems like it never manages to put the mod list together Mod List: ~~ERROR~~ NullPointerException: null but maybe thats done at a point it hasnt reached" 

and lastly this
"java.lang.NoClassDefFoundError means a class definition cant be found :P
but i dont know why that would be
its possible the mod is broken i suppose, or that your forge version is not compatible".

But here's crash report so you can look into it https://pastebin.com/aLqr6J7j

Many thanks in advance :)

**Comment by BluSunrize** [comment]
We do not support Optifine, and I'm afraid we do not offer support if you aren't using the latest version of IE.
If you can't reproduce this issue with version 0.14-94, then there's nothing to be done here.

**Comment by malte0811** [comment]
The initial release had the same Forge version requirements as the newer release, we just forgot to specify the minimum Forge version before the release. The crash is because we need classes added in newer Forge versions.  
As a note, you probably wouldn't have had much fun with IE and Optifine in any case: https://github.com/sp614x/optifine/issues/3548

**Comment by jillv46** [comment]
So how come the other version crashes? Is there a bug in it or something? If yes is it possible to make the latest version work on version 28.2.1 or?

**Comment by BluSunrize** [comment]
No, it's not. Malte literally just said

> we we need classes added in newer Forge versions.
